name: Update Workflow Options

on:
  schedule:
    - cron: '0 9 * * 1' # Ogni lunedì alle 09:00
  workflow_dispatch:   # Permette l'avvio manuale

jobs:
  update-options:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.MY_SECRET }}
          persist-credentials: true # Fondamentale per poter fare il push dopo

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install pyyaml requests

      - name: Update workflow options
        run: python .github/workflows/update-workflow-options.py

      - name: Commit and Push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          # Verifica se ci sono cambiamenti prima di fare il commit
          if git diff --quiet .github/workflows/build-image.yml; then
            echo "Nessuna modifica rilevata."
          else
            git add .github/workflows/build-image.yml
            git commit -m "ci: update workflow options [skip ci]"
            git push origin main
            echo "Modifiche inviate direttamente al main."
          fi